name: LINUX

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: MinSizeRel

jobs:
  linux-native:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install OpenGL
      run: apt install mesa-common-dev libgl1-mesa-dev

    - name: Configure CMake
      run: cmake -Bbuild -H. -DCMAKE_BUILD_TYPE=MinSizeRel 

    - name: Build
      run: cmake --build build/ -j20

    - name: Release
      uses: fnkr/github-action-ghr@v1.3
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GHR_COMPRESS: zip
        GHR_PATH: build/
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}